package test;

// Generated Mar 12, 2016 8:10:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompanywithinfoId generated by hbm2java
 */
@Embeddable
public class CompanywithinfoId implements java.io.Serializable {

	@Column(name = "id", nullable = false)
	private int id;

	@Column(name = "businessName", nullable = false, length = 100)
	private String businessName;

	@Column(name = "category", length = 50)
	private String category;

	@Column(name = "city", length = 30)
	private String city;

	@Column(name = "province", length = 20)
	private String province;

	@Column(name = "country", length = 20)
	private String country;

	@Column(name = "website", length = 80)
	private String website;

	@Column(name = "isCustomer")
	private Boolean isCustomer;

	@Column(name = "isSupplier")
	private Boolean isSupplier;

	@Column(name = "status")
	private Integer status;

	@Column(name = "repId")
	private Integer repId;

	@Column(name = "csrId")
	private Integer csrId;

	@Column(name = "discount")
	private BigDecimal discount;

	@Column(name = "term", length = 50)
	private String term;

	@Column(name = "useWsp")
	private Boolean useWsp;

	@Column(name = "repFirstName")
	private String repFirstName;

	@Column(name = "repLastName")
	private String repLastName;

	@Column(name = "csrFirstName")
	private String csrFirstName;

	@Column(name = "csrLastName")
	private String csrLastName;

	public CompanywithinfoId() {
	}

	public CompanywithinfoId(int id, String businessName) {
		this.id = id;
		this.businessName = businessName;
	}

	public CompanywithinfoId(int id, String businessName, String category,
			String city, String province, String country, String website,
			Boolean isCustomer, Boolean isSupplier, Integer status,
			Integer repId, Integer csrId, BigDecimal discount, String term,
			Boolean useWsp, String repFirstName, String repLastName,
			String csrFirstName, String csrLastName) {
		this.id = id;
		this.businessName = businessName;
		this.category = category;
		this.city = city;
		this.province = province;
		this.country = country;
		this.website = website;
		this.isCustomer = isCustomer;
		this.isSupplier = isSupplier;
		this.status = status;
		this.repId = repId;
		this.csrId = csrId;
		this.discount = discount;
		this.term = term;
		this.useWsp = useWsp;
		this.repFirstName = repFirstName;
		this.repLastName = repLastName;
		this.csrFirstName = csrFirstName;
		this.csrLastName = csrLastName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Boolean getIsCustomer() {
		return this.isCustomer;
	}

	public void setIsCustomer(Boolean isCustomer) {
		this.isCustomer = isCustomer;
	}

	public Boolean getIsSupplier() {
		return this.isSupplier;
	}

	public void setIsSupplier(Boolean isSupplier) {
		this.isSupplier = isSupplier;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getRepId() {
		return this.repId;
	}

	public void setRepId(Integer repId) {
		this.repId = repId;
	}

	public Integer getCsrId() {
		return this.csrId;
	}

	public void setCsrId(Integer csrId) {
		this.csrId = csrId;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	public Boolean getUseWsp() {
		return this.useWsp;
	}

	public void setUseWsp(Boolean useWsp) {
		this.useWsp = useWsp;
	}

	public String getRepFirstName() {
		return this.repFirstName;
	}

	public void setRepFirstName(String repFirstName) {
		this.repFirstName = repFirstName;
	}

	public String getRepLastName() {
		return this.repLastName;
	}

	public void setRepLastName(String repLastName) {
		this.repLastName = repLastName;
	}

	public String getCsrFirstName() {
		return this.csrFirstName;
	}

	public void setCsrFirstName(String csrFirstName) {
		this.csrFirstName = csrFirstName;
	}

	public String getCsrLastName() {
		return this.csrLastName;
	}

	public void setCsrLastName(String csrLastName) {
		this.csrLastName = csrLastName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CompanywithinfoId))
			return false;
		CompanywithinfoId castOther = (CompanywithinfoId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getBusinessName() == castOther.getBusinessName()) || (this
						.getBusinessName() != null
						&& castOther.getBusinessName() != null && this
						.getBusinessName().equals(castOther.getBusinessName())))
				&& ((this.getCategory() == castOther.getCategory()) || (this
						.getCategory() != null
						&& castOther.getCategory() != null && this
						.getCategory().equals(castOther.getCategory())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null
						&& castOther.getCity() != null && this.getCity()
						.equals(castOther.getCity())))
				&& ((this.getProvince() == castOther.getProvince()) || (this
						.getProvince() != null
						&& castOther.getProvince() != null && this
						.getProvince().equals(castOther.getProvince())))
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())))
				&& ((this.getWebsite() == castOther.getWebsite()) || (this
						.getWebsite() != null && castOther.getWebsite() != null && this
						.getWebsite().equals(castOther.getWebsite())))
				&& ((this.getIsCustomer() == castOther.getIsCustomer()) || (this
						.getIsCustomer() != null
						&& castOther.getIsCustomer() != null && this
						.getIsCustomer().equals(castOther.getIsCustomer())))
				&& ((this.getIsSupplier() == castOther.getIsSupplier()) || (this
						.getIsSupplier() != null
						&& castOther.getIsSupplier() != null && this
						.getIsSupplier().equals(castOther.getIsSupplier())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getRepId() == castOther.getRepId()) || (this
						.getRepId() != null && castOther.getRepId() != null && this
						.getRepId().equals(castOther.getRepId())))
				&& ((this.getCsrId() == castOther.getCsrId()) || (this
						.getCsrId() != null && castOther.getCsrId() != null && this
						.getCsrId().equals(castOther.getCsrId())))
				&& ((this.getDiscount() == castOther.getDiscount()) || (this
						.getDiscount() != null
						&& castOther.getDiscount() != null && this
						.getDiscount().equals(castOther.getDiscount())))
				&& ((this.getTerm() == castOther.getTerm()) || (this.getTerm() != null
						&& castOther.getTerm() != null && this.getTerm()
						.equals(castOther.getTerm())))
				&& ((this.getUseWsp() == castOther.getUseWsp()) || (this
						.getUseWsp() != null && castOther.getUseWsp() != null && this
						.getUseWsp().equals(castOther.getUseWsp())))
				&& ((this.getRepFirstName() == castOther.getRepFirstName()) || (this
						.getRepFirstName() != null
						&& castOther.getRepFirstName() != null && this
						.getRepFirstName().equals(castOther.getRepFirstName())))
				&& ((this.getRepLastName() == castOther.getRepLastName()) || (this
						.getRepLastName() != null
						&& castOther.getRepLastName() != null && this
						.getRepLastName().equals(castOther.getRepLastName())))
				&& ((this.getCsrFirstName() == castOther.getCsrFirstName()) || (this
						.getCsrFirstName() != null
						&& castOther.getCsrFirstName() != null && this
						.getCsrFirstName().equals(castOther.getCsrFirstName())))
				&& ((this.getCsrLastName() == castOther.getCsrLastName()) || (this
						.getCsrLastName() != null
						&& castOther.getCsrLastName() != null && this
						.getCsrLastName().equals(castOther.getCsrLastName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37
				* result
				+ (getBusinessName() == null ? 0 : this.getBusinessName()
						.hashCode());
		result = 37 * result
				+ (getCategory() == null ? 0 : this.getCategory().hashCode());
		result = 37 * result
				+ (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result
				+ (getProvince() == null ? 0 : this.getProvince().hashCode());
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result
				+ (getWebsite() == null ? 0 : this.getWebsite().hashCode());
		result = 37
				* result
				+ (getIsCustomer() == null ? 0 : this.getIsCustomer()
						.hashCode());
		result = 37
				* result
				+ (getIsSupplier() == null ? 0 : this.getIsSupplier()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getRepId() == null ? 0 : this.getRepId().hashCode());
		result = 37 * result
				+ (getCsrId() == null ? 0 : this.getCsrId().hashCode());
		result = 37 * result
				+ (getDiscount() == null ? 0 : this.getDiscount().hashCode());
		result = 37 * result
				+ (getTerm() == null ? 0 : this.getTerm().hashCode());
		result = 37 * result
				+ (getUseWsp() == null ? 0 : this.getUseWsp().hashCode());
		result = 37
				* result
				+ (getRepFirstName() == null ? 0 : this.getRepFirstName()
						.hashCode());
		result = 37
				* result
				+ (getRepLastName() == null ? 0 : this.getRepLastName()
						.hashCode());
		result = 37
				* result
				+ (getCsrFirstName() == null ? 0 : this.getCsrFirstName()
						.hashCode());
		result = 37
				* result
				+ (getCsrLastName() == null ? 0 : this.getCsrLastName()
						.hashCode());
		return result;
	}

}
