package test;

// Generated Mar 12, 2016 8:10:40 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GarmentwithdetailId generated by hbm2java
 */
@Embeddable
public class GarmentwithdetailId implements java.io.Serializable {

	@Column(name = "garmentId", nullable = false)
	private int garmentId;

	@Column(name = "styleNo", nullable = false, length = 20)
	private String styleNo;

	@Column(name = "styleName", length = 50)
	private String styleName;

	@Column(name = "brandId")
	private Integer brandId;

	@Column(name = "brand", length = 50)
	private String brand;

	@Column(name = "seasonId")
	private Integer seasonId;

	@Column(name = "season", length = 50)
	private String season;

	@Column(name = "category", length = 30)
	private String category;

	@Column(name = "upcId", nullable = false)
	private int upcId;

	@Column(name = "upcNo", length = 12)
	private String upcNo;

	@Column(name = "colour", nullable = false, length = 50)
	private String colour;

	@Column(name = "size", nullable = false, length = 10)
	private String size;

	@Column(name = "qoh")
	private Integer qoh;

	@Column(name = "sq")
	private Integer sq;

	@Column(name = "pq")
	private Integer pq;

	@Column(name = "rrp", precision = 22, scale = 0)
	private Double rrp;

	@Column(name = "wsp", precision = 22, scale = 0)
	private Double wsp;

	public GarmentwithdetailId() {
	}

	public GarmentwithdetailId(int garmentId, String styleNo, int upcId,
			String colour, String size) {
		this.garmentId = garmentId;
		this.styleNo = styleNo;
		this.upcId = upcId;
		this.colour = colour;
		this.size = size;
	}

	public GarmentwithdetailId(int garmentId, String styleNo, String styleName,
			Integer brandId, String brand, Integer seasonId, String season,
			String category, int upcId, String upcNo, String colour,
			String size, Integer qoh, Integer sq, Integer pq, Double rrp,
			Double wsp) {
		this.garmentId = garmentId;
		this.styleNo = styleNo;
		this.styleName = styleName;
		this.brandId = brandId;
		this.brand = brand;
		this.seasonId = seasonId;
		this.season = season;
		this.category = category;
		this.upcId = upcId;
		this.upcNo = upcNo;
		this.colour = colour;
		this.size = size;
		this.qoh = qoh;
		this.sq = sq;
		this.pq = pq;
		this.rrp = rrp;
		this.wsp = wsp;
	}

	public int getGarmentId() {
		return this.garmentId;
	}

	public void setGarmentId(int garmentId) {
		this.garmentId = garmentId;
	}

	public String getStyleNo() {
		return this.styleNo;
	}

	public void setStyleNo(String styleNo) {
		this.styleNo = styleNo;
	}

	public String getStyleName() {
		return this.styleName;
	}

	public void setStyleName(String styleName) {
		this.styleName = styleName;
	}

	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public Integer getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(Integer seasonId) {
		this.seasonId = seasonId;
	}

	public String getSeason() {
		return this.season;
	}

	public void setSeason(String season) {
		this.season = season;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public int getUpcId() {
		return this.upcId;
	}

	public void setUpcId(int upcId) {
		this.upcId = upcId;
	}

	public String getUpcNo() {
		return this.upcNo;
	}

	public void setUpcNo(String upcNo) {
		this.upcNo = upcNo;
	}

	public String getColour() {
		return this.colour;
	}

	public void setColour(String colour) {
		this.colour = colour;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public Integer getQoh() {
		return this.qoh;
	}

	public void setQoh(Integer qoh) {
		this.qoh = qoh;
	}

	public Integer getSq() {
		return this.sq;
	}

	public void setSq(Integer sq) {
		this.sq = sq;
	}

	public Integer getPq() {
		return this.pq;
	}

	public void setPq(Integer pq) {
		this.pq = pq;
	}

	public Double getRrp() {
		return this.rrp;
	}

	public void setRrp(Double rrp) {
		this.rrp = rrp;
	}

	public Double getWsp() {
		return this.wsp;
	}

	public void setWsp(Double wsp) {
		this.wsp = wsp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GarmentwithdetailId))
			return false;
		GarmentwithdetailId castOther = (GarmentwithdetailId) other;

		return (this.getGarmentId() == castOther.getGarmentId())
				&& ((this.getStyleNo() == castOther.getStyleNo()) || (this
						.getStyleNo() != null && castOther.getStyleNo() != null && this
						.getStyleNo().equals(castOther.getStyleNo())))
				&& ((this.getStyleName() == castOther.getStyleName()) || (this
						.getStyleName() != null
						&& castOther.getStyleName() != null && this
						.getStyleName().equals(castOther.getStyleName())))
				&& ((this.getBrandId() == castOther.getBrandId()) || (this
						.getBrandId() != null && castOther.getBrandId() != null && this
						.getBrandId().equals(castOther.getBrandId())))
				&& ((this.getBrand() == castOther.getBrand()) || (this
						.getBrand() != null && castOther.getBrand() != null && this
						.getBrand().equals(castOther.getBrand())))
				&& ((this.getSeasonId() == castOther.getSeasonId()) || (this
						.getSeasonId() != null
						&& castOther.getSeasonId() != null && this
						.getSeasonId().equals(castOther.getSeasonId())))
				&& ((this.getSeason() == castOther.getSeason()) || (this
						.getSeason() != null && castOther.getSeason() != null && this
						.getSeason().equals(castOther.getSeason())))
				&& ((this.getCategory() == castOther.getCategory()) || (this
						.getCategory() != null
						&& castOther.getCategory() != null && this
						.getCategory().equals(castOther.getCategory())))
				&& (this.getUpcId() == castOther.getUpcId())
				&& ((this.getUpcNo() == castOther.getUpcNo()) || (this
						.getUpcNo() != null && castOther.getUpcNo() != null && this
						.getUpcNo().equals(castOther.getUpcNo())))
				&& ((this.getColour() == castOther.getColour()) || (this
						.getColour() != null && castOther.getColour() != null && this
						.getColour().equals(castOther.getColour())))
				&& ((this.getSize() == castOther.getSize()) || (this.getSize() != null
						&& castOther.getSize() != null && this.getSize()
						.equals(castOther.getSize())))
				&& ((this.getQoh() == castOther.getQoh()) || (this.getQoh() != null
						&& castOther.getQoh() != null && this.getQoh().equals(
						castOther.getQoh())))
				&& ((this.getSq() == castOther.getSq()) || (this.getSq() != null
						&& castOther.getSq() != null && this.getSq().equals(
						castOther.getSq())))
				&& ((this.getPq() == castOther.getPq()) || (this.getPq() != null
						&& castOther.getPq() != null && this.getPq().equals(
						castOther.getPq())))
				&& ((this.getRrp() == castOther.getRrp()) || (this.getRrp() != null
						&& castOther.getRrp() != null && this.getRrp().equals(
						castOther.getRrp())))
				&& ((this.getWsp() == castOther.getWsp()) || (this.getWsp() != null
						&& castOther.getWsp() != null && this.getWsp().equals(
						castOther.getWsp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGarmentId();
		result = 37 * result
				+ (getStyleNo() == null ? 0 : this.getStyleNo().hashCode());
		result = 37 * result
				+ (getStyleName() == null ? 0 : this.getStyleName().hashCode());
		result = 37 * result
				+ (getBrandId() == null ? 0 : this.getBrandId().hashCode());
		result = 37 * result
				+ (getBrand() == null ? 0 : this.getBrand().hashCode());
		result = 37 * result
				+ (getSeasonId() == null ? 0 : this.getSeasonId().hashCode());
		result = 37 * result
				+ (getSeason() == null ? 0 : this.getSeason().hashCode());
		result = 37 * result
				+ (getCategory() == null ? 0 : this.getCategory().hashCode());
		result = 37 * result + this.getUpcId();
		result = 37 * result
				+ (getUpcNo() == null ? 0 : this.getUpcNo().hashCode());
		result = 37 * result
				+ (getColour() == null ? 0 : this.getColour().hashCode());
		result = 37 * result
				+ (getSize() == null ? 0 : this.getSize().hashCode());
		result = 37 * result
				+ (getQoh() == null ? 0 : this.getQoh().hashCode());
		result = 37 * result + (getSq() == null ? 0 : this.getSq().hashCode());
		result = 37 * result + (getPq() == null ? 0 : this.getPq().hashCode());
		result = 37 * result
				+ (getRrp() == null ? 0 : this.getRrp().hashCode());
		result = 37 * result
				+ (getWsp() == null ? 0 : this.getWsp().hashCode());
		return result;
	}

}
