package test;

// Generated Mar 12, 2016 8:10:40 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Garmentwithdetail generated by hbm2java
 */
@Entity
@Table(name = "garmentwithdetail", catalog = "world")
public class Garmentwithdetail implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "garmentId", column = @Column(name = "garmentId", nullable = false)),
			@AttributeOverride(name = "styleNo", column = @Column(name = "styleNo", nullable = false, length = 20)),
			@AttributeOverride(name = "styleName", column = @Column(name = "styleName", length = 50)),
			@AttributeOverride(name = "brandId", column = @Column(name = "brandId")),
			@AttributeOverride(name = "brand", column = @Column(name = "brand", length = 50)),
			@AttributeOverride(name = "seasonId", column = @Column(name = "seasonId")),
			@AttributeOverride(name = "season", column = @Column(name = "season", length = 50)),
			@AttributeOverride(name = "category", column = @Column(name = "category", length = 30)),
			@AttributeOverride(name = "upcId", column = @Column(name = "upcId", nullable = false)),
			@AttributeOverride(name = "upcNo", column = @Column(name = "upcNo", length = 12)),
			@AttributeOverride(name = "colour", column = @Column(name = "colour", nullable = false, length = 50)),
			@AttributeOverride(name = "size", column = @Column(name = "size", nullable = false, length = 10)),
			@AttributeOverride(name = "qoh", column = @Column(name = "qoh")),
			@AttributeOverride(name = "sq", column = @Column(name = "sq")),
			@AttributeOverride(name = "pq", column = @Column(name = "pq")),
			@AttributeOverride(name = "rrp", column = @Column(name = "rrp", precision = 22, scale = 0)),
			@AttributeOverride(name = "wsp", column = @Column(name = "wsp", precision = 22, scale = 0)) })
	private GarmentwithdetailId id;

	public Garmentwithdetail() {
	}

	public Garmentwithdetail(GarmentwithdetailId id) {
		this.id = id;
	}

	public GarmentwithdetailId getId() {
		return this.id;
	}

	public void setId(GarmentwithdetailId id) {
		this.id = id;
	}

}
