package test;

// Generated Mar 12, 2016 8:10:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderbillitemviewId generated by hbm2java
 */
@Embeddable
public class OrderbillitemviewId implements java.io.Serializable {

	@Column(name = "rowId", nullable = false)
	private int rowId;

	@Column(name = "description")
	private String description;

	@Column(name = "finishAmt")
	private BigDecimal finishAmt;

	@Column(name = "finishQty")
	private BigDecimal finishQty;

	@Column(name = "invoiceAmt")
	private BigDecimal invoiceAmt;

	@Column(name = "invoicePrice")
	private BigDecimal invoicePrice;

	@Column(name = "invoiceQty")
	private BigDecimal invoiceQty;

	@Column(name = "itemNumber", length = 20)
	private String itemNumber;

	@Column(name = "lineNo")
	private Integer lineNo;

	@Column(name = "orderAmt")
	private BigDecimal orderAmt;

	@Column(name = "orderItemId")
	private Integer orderItemId;

	@Column(name = "orderPrice")
	private BigDecimal orderPrice;

	@Column(name = "orderQty")
	private BigDecimal orderQty;

	@Column(name = "remark")
	private String remark;

	@Column(name = "snpId")
	private Integer snpId;

	@Column(name = "unit", length = 20)
	private String unit;

	@Column(name = "billingKey", length = 20)
	private String billingKey;

	@Column(name = "itemTypeId")
	private Integer itemTypeId;

	@Column(name = "dsicount")
	private BigDecimal dsicount;

	@Column(name = "listPrice")
	private BigDecimal listPrice;

	@Column(name = "orderId", nullable = false)
	private int orderId;

	@Column(name = "buyer", length = 50)
	private String buyer;

	@Column(name = "creatorId")
	private Integer creatorId;

	@Column(name = "customerId")
	private Integer customerId;

	@Column(name = "customerPO", length = 50)
	private String customerPo;

	@Column(name = "finishBy")
	private Integer finishBy;

	@Column(name = "finishDate", length = 10)
	private Date finishDate;

	@Column(name = "invoiceBy")
	private Integer invoiceBy;

	@Column(name = "invoiceDate", length = 10)
	private Date invoiceDate;

	@Column(name = "orderDate", length = 10)
	private Date orderDate;

	@Column(name = "orderName", length = 100)
	private String orderName;

	@Column(name = "orderNumber", nullable = false, length = 20)
	private String orderNumber;

	@Column(name = "orderStatus")
	private Integer orderStatus;

	@Column(name = "orderTime", length = 8)
	private Date orderTime;

	@Column(name = "repId")
	private Integer repId;

	@Column(name = "requireDate", length = 10)
	private Date requireDate;

	@Column(name = "requireTime", length = 8)
	private Date requireTime;

	@Column(name = "businessName", length = 100)
	private String businessName;

	@Column(name = "creator", length = 511)
	private String creator;

	@Column(name = "rep", length = 511)
	private String rep;

	@Column(name = "snp", length = 50)
	private String snp;

	public OrderbillitemviewId() {
	}

	public OrderbillitemviewId(int rowId, int orderId, String orderNumber) {
		this.rowId = rowId;
		this.orderId = orderId;
		this.orderNumber = orderNumber;
	}

	public OrderbillitemviewId(int rowId, String description,
			BigDecimal finishAmt, BigDecimal finishQty, BigDecimal invoiceAmt,
			BigDecimal invoicePrice, BigDecimal invoiceQty, String itemNumber,
			Integer lineNo, BigDecimal orderAmt, Integer orderItemId,
			BigDecimal orderPrice, BigDecimal orderQty, String remark,
			Integer snpId, String unit, String billingKey, Integer itemTypeId,
			BigDecimal dsicount, BigDecimal listPrice, int orderId,
			String buyer, Integer creatorId, Integer customerId,
			String customerPo, Integer finishBy, Date finishDate,
			Integer invoiceBy, Date invoiceDate, Date orderDate,
			String orderName, String orderNumber, Integer orderStatus,
			Date orderTime, Integer repId, Date requireDate, Date requireTime,
			String businessName, String creator, String rep, String snp) {
		this.rowId = rowId;
		this.description = description;
		this.finishAmt = finishAmt;
		this.finishQty = finishQty;
		this.invoiceAmt = invoiceAmt;
		this.invoicePrice = invoicePrice;
		this.invoiceQty = invoiceQty;
		this.itemNumber = itemNumber;
		this.lineNo = lineNo;
		this.orderAmt = orderAmt;
		this.orderItemId = orderItemId;
		this.orderPrice = orderPrice;
		this.orderQty = orderQty;
		this.remark = remark;
		this.snpId = snpId;
		this.unit = unit;
		this.billingKey = billingKey;
		this.itemTypeId = itemTypeId;
		this.dsicount = dsicount;
		this.listPrice = listPrice;
		this.orderId = orderId;
		this.buyer = buyer;
		this.creatorId = creatorId;
		this.customerId = customerId;
		this.customerPo = customerPo;
		this.finishBy = finishBy;
		this.finishDate = finishDate;
		this.invoiceBy = invoiceBy;
		this.invoiceDate = invoiceDate;
		this.orderDate = orderDate;
		this.orderName = orderName;
		this.orderNumber = orderNumber;
		this.orderStatus = orderStatus;
		this.orderTime = orderTime;
		this.repId = repId;
		this.requireDate = requireDate;
		this.requireTime = requireTime;
		this.businessName = businessName;
		this.creator = creator;
		this.rep = rep;
		this.snp = snp;
	}

	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getFinishAmt() {
		return this.finishAmt;
	}

	public void setFinishAmt(BigDecimal finishAmt) {
		this.finishAmt = finishAmt;
	}

	public BigDecimal getFinishQty() {
		return this.finishQty;
	}

	public void setFinishQty(BigDecimal finishQty) {
		this.finishQty = finishQty;
	}

	public BigDecimal getInvoiceAmt() {
		return this.invoiceAmt;
	}

	public void setInvoiceAmt(BigDecimal invoiceAmt) {
		this.invoiceAmt = invoiceAmt;
	}

	public BigDecimal getInvoicePrice() {
		return this.invoicePrice;
	}

	public void setInvoicePrice(BigDecimal invoicePrice) {
		this.invoicePrice = invoicePrice;
	}

	public BigDecimal getInvoiceQty() {
		return this.invoiceQty;
	}

	public void setInvoiceQty(BigDecimal invoiceQty) {
		this.invoiceQty = invoiceQty;
	}

	public String getItemNumber() {
		return this.itemNumber;
	}

	public void setItemNumber(String itemNumber) {
		this.itemNumber = itemNumber;
	}

	public Integer getLineNo() {
		return this.lineNo;
	}

	public void setLineNo(Integer lineNo) {
		this.lineNo = lineNo;
	}

	public BigDecimal getOrderAmt() {
		return this.orderAmt;
	}

	public void setOrderAmt(BigDecimal orderAmt) {
		this.orderAmt = orderAmt;
	}

	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	public BigDecimal getOrderQty() {
		return this.orderQty;
	}

	public void setOrderQty(BigDecimal orderQty) {
		this.orderQty = orderQty;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getSnpId() {
		return this.snpId;
	}

	public void setSnpId(Integer snpId) {
		this.snpId = snpId;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getBillingKey() {
		return this.billingKey;
	}

	public void setBillingKey(String billingKey) {
		this.billingKey = billingKey;
	}

	public Integer getItemTypeId() {
		return this.itemTypeId;
	}

	public void setItemTypeId(Integer itemTypeId) {
		this.itemTypeId = itemTypeId;
	}

	public BigDecimal getDsicount() {
		return this.dsicount;
	}

	public void setDsicount(BigDecimal dsicount) {
		this.dsicount = dsicount;
	}

	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public String getBuyer() {
		return this.buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	public Integer getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getCustomerPo() {
		return this.customerPo;
	}

	public void setCustomerPo(String customerPo) {
		this.customerPo = customerPo;
	}

	public Integer getFinishBy() {
		return this.finishBy;
	}

	public void setFinishBy(Integer finishBy) {
		this.finishBy = finishBy;
	}

	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	public Integer getInvoiceBy() {
		return this.invoiceBy;
	}

	public void setInvoiceBy(Integer invoiceBy) {
		this.invoiceBy = invoiceBy;
	}

	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public Integer getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Integer getRepId() {
		return this.repId;
	}

	public void setRepId(Integer repId) {
		this.repId = repId;
	}

	public Date getRequireDate() {
		return this.requireDate;
	}

	public void setRequireDate(Date requireDate) {
		this.requireDate = requireDate;
	}

	public Date getRequireTime() {
		return this.requireTime;
	}

	public void setRequireTime(Date requireTime) {
		this.requireTime = requireTime;
	}

	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getRep() {
		return this.rep;
	}

	public void setRep(String rep) {
		this.rep = rep;
	}

	public String getSnp() {
		return this.snp;
	}

	public void setSnp(String snp) {
		this.snp = snp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderbillitemviewId))
			return false;
		OrderbillitemviewId castOther = (OrderbillitemviewId) other;

		return (this.getRowId() == castOther.getRowId())
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getFinishAmt() == castOther.getFinishAmt()) || (this
						.getFinishAmt() != null
						&& castOther.getFinishAmt() != null && this
						.getFinishAmt().equals(castOther.getFinishAmt())))
				&& ((this.getFinishQty() == castOther.getFinishQty()) || (this
						.getFinishQty() != null
						&& castOther.getFinishQty() != null && this
						.getFinishQty().equals(castOther.getFinishQty())))
				&& ((this.getInvoiceAmt() == castOther.getInvoiceAmt()) || (this
						.getInvoiceAmt() != null
						&& castOther.getInvoiceAmt() != null && this
						.getInvoiceAmt().equals(castOther.getInvoiceAmt())))
				&& ((this.getInvoicePrice() == castOther.getInvoicePrice()) || (this
						.getInvoicePrice() != null
						&& castOther.getInvoicePrice() != null && this
						.getInvoicePrice().equals(castOther.getInvoicePrice())))
				&& ((this.getInvoiceQty() == castOther.getInvoiceQty()) || (this
						.getInvoiceQty() != null
						&& castOther.getInvoiceQty() != null && this
						.getInvoiceQty().equals(castOther.getInvoiceQty())))
				&& ((this.getItemNumber() == castOther.getItemNumber()) || (this
						.getItemNumber() != null
						&& castOther.getItemNumber() != null && this
						.getItemNumber().equals(castOther.getItemNumber())))
				&& ((this.getLineNo() == castOther.getLineNo()) || (this
						.getLineNo() != null && castOther.getLineNo() != null && this
						.getLineNo().equals(castOther.getLineNo())))
				&& ((this.getOrderAmt() == castOther.getOrderAmt()) || (this
						.getOrderAmt() != null
						&& castOther.getOrderAmt() != null && this
						.getOrderAmt().equals(castOther.getOrderAmt())))
				&& ((this.getOrderItemId() == castOther.getOrderItemId()) || (this
						.getOrderItemId() != null
						&& castOther.getOrderItemId() != null && this
						.getOrderItemId().equals(castOther.getOrderItemId())))
				&& ((this.getOrderPrice() == castOther.getOrderPrice()) || (this
						.getOrderPrice() != null
						&& castOther.getOrderPrice() != null && this
						.getOrderPrice().equals(castOther.getOrderPrice())))
				&& ((this.getOrderQty() == castOther.getOrderQty()) || (this
						.getOrderQty() != null
						&& castOther.getOrderQty() != null && this
						.getOrderQty().equals(castOther.getOrderQty())))
				&& ((this.getRemark() == castOther.getRemark()) || (this
						.getRemark() != null && castOther.getRemark() != null && this
						.getRemark().equals(castOther.getRemark())))
				&& ((this.getSnpId() == castOther.getSnpId()) || (this
						.getSnpId() != null && castOther.getSnpId() != null && this
						.getSnpId().equals(castOther.getSnpId())))
				&& ((this.getUnit() == castOther.getUnit()) || (this.getUnit() != null
						&& castOther.getUnit() != null && this.getUnit()
						.equals(castOther.getUnit())))
				&& ((this.getBillingKey() == castOther.getBillingKey()) || (this
						.getBillingKey() != null
						&& castOther.getBillingKey() != null && this
						.getBillingKey().equals(castOther.getBillingKey())))
				&& ((this.getItemTypeId() == castOther.getItemTypeId()) || (this
						.getItemTypeId() != null
						&& castOther.getItemTypeId() != null && this
						.getItemTypeId().equals(castOther.getItemTypeId())))
				&& ((this.getDsicount() == castOther.getDsicount()) || (this
						.getDsicount() != null
						&& castOther.getDsicount() != null && this
						.getDsicount().equals(castOther.getDsicount())))
				&& ((this.getListPrice() == castOther.getListPrice()) || (this
						.getListPrice() != null
						&& castOther.getListPrice() != null && this
						.getListPrice().equals(castOther.getListPrice())))
				&& (this.getOrderId() == castOther.getOrderId())
				&& ((this.getBuyer() == castOther.getBuyer()) || (this
						.getBuyer() != null && castOther.getBuyer() != null && this
						.getBuyer().equals(castOther.getBuyer())))
				&& ((this.getCreatorId() == castOther.getCreatorId()) || (this
						.getCreatorId() != null
						&& castOther.getCreatorId() != null && this
						.getCreatorId().equals(castOther.getCreatorId())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this
						.getCustomerId() != null
						&& castOther.getCustomerId() != null && this
						.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCustomerPo() == castOther.getCustomerPo()) || (this
						.getCustomerPo() != null
						&& castOther.getCustomerPo() != null && this
						.getCustomerPo().equals(castOther.getCustomerPo())))
				&& ((this.getFinishBy() == castOther.getFinishBy()) || (this
						.getFinishBy() != null
						&& castOther.getFinishBy() != null && this
						.getFinishBy().equals(castOther.getFinishBy())))
				&& ((this.getFinishDate() == castOther.getFinishDate()) || (this
						.getFinishDate() != null
						&& castOther.getFinishDate() != null && this
						.getFinishDate().equals(castOther.getFinishDate())))
				&& ((this.getInvoiceBy() == castOther.getInvoiceBy()) || (this
						.getInvoiceBy() != null
						&& castOther.getInvoiceBy() != null && this
						.getInvoiceBy().equals(castOther.getInvoiceBy())))
				&& ((this.getInvoiceDate() == castOther.getInvoiceDate()) || (this
						.getInvoiceDate() != null
						&& castOther.getInvoiceDate() != null && this
						.getInvoiceDate().equals(castOther.getInvoiceDate())))
				&& ((this.getOrderDate() == castOther.getOrderDate()) || (this
						.getOrderDate() != null
						&& castOther.getOrderDate() != null && this
						.getOrderDate().equals(castOther.getOrderDate())))
				&& ((this.getOrderName() == castOther.getOrderName()) || (this
						.getOrderName() != null
						&& castOther.getOrderName() != null && this
						.getOrderName().equals(castOther.getOrderName())))
				&& ((this.getOrderNumber() == castOther.getOrderNumber()) || (this
						.getOrderNumber() != null
						&& castOther.getOrderNumber() != null && this
						.getOrderNumber().equals(castOther.getOrderNumber())))
				&& ((this.getOrderStatus() == castOther.getOrderStatus()) || (this
						.getOrderStatus() != null
						&& castOther.getOrderStatus() != null && this
						.getOrderStatus().equals(castOther.getOrderStatus())))
				&& ((this.getOrderTime() == castOther.getOrderTime()) || (this
						.getOrderTime() != null
						&& castOther.getOrderTime() != null && this
						.getOrderTime().equals(castOther.getOrderTime())))
				&& ((this.getRepId() == castOther.getRepId()) || (this
						.getRepId() != null && castOther.getRepId() != null && this
						.getRepId().equals(castOther.getRepId())))
				&& ((this.getRequireDate() == castOther.getRequireDate()) || (this
						.getRequireDate() != null
						&& castOther.getRequireDate() != null && this
						.getRequireDate().equals(castOther.getRequireDate())))
				&& ((this.getRequireTime() == castOther.getRequireTime()) || (this
						.getRequireTime() != null
						&& castOther.getRequireTime() != null && this
						.getRequireTime().equals(castOther.getRequireTime())))
				&& ((this.getBusinessName() == castOther.getBusinessName()) || (this
						.getBusinessName() != null
						&& castOther.getBusinessName() != null && this
						.getBusinessName().equals(castOther.getBusinessName())))
				&& ((this.getCreator() == castOther.getCreator()) || (this
						.getCreator() != null && castOther.getCreator() != null && this
						.getCreator().equals(castOther.getCreator())))
				&& ((this.getRep() == castOther.getRep()) || (this.getRep() != null
						&& castOther.getRep() != null && this.getRep().equals(
						castOther.getRep())))
				&& ((this.getSnp() == castOther.getSnp()) || (this.getSnp() != null
						&& castOther.getSnp() != null && this.getSnp().equals(
						castOther.getSnp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRowId();
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getFinishAmt() == null ? 0 : this.getFinishAmt().hashCode());
		result = 37 * result
				+ (getFinishQty() == null ? 0 : this.getFinishQty().hashCode());
		result = 37
				* result
				+ (getInvoiceAmt() == null ? 0 : this.getInvoiceAmt()
						.hashCode());
		result = 37
				* result
				+ (getInvoicePrice() == null ? 0 : this.getInvoicePrice()
						.hashCode());
		result = 37
				* result
				+ (getInvoiceQty() == null ? 0 : this.getInvoiceQty()
						.hashCode());
		result = 37
				* result
				+ (getItemNumber() == null ? 0 : this.getItemNumber()
						.hashCode());
		result = 37 * result
				+ (getLineNo() == null ? 0 : this.getLineNo().hashCode());
		result = 37 * result
				+ (getOrderAmt() == null ? 0 : this.getOrderAmt().hashCode());
		result = 37
				* result
				+ (getOrderItemId() == null ? 0 : this.getOrderItemId()
						.hashCode());
		result = 37
				* result
				+ (getOrderPrice() == null ? 0 : this.getOrderPrice()
						.hashCode());
		result = 37 * result
				+ (getOrderQty() == null ? 0 : this.getOrderQty().hashCode());
		result = 37 * result
				+ (getRemark() == null ? 0 : this.getRemark().hashCode());
		result = 37 * result
				+ (getSnpId() == null ? 0 : this.getSnpId().hashCode());
		result = 37 * result
				+ (getUnit() == null ? 0 : this.getUnit().hashCode());
		result = 37
				* result
				+ (getBillingKey() == null ? 0 : this.getBillingKey()
						.hashCode());
		result = 37
				* result
				+ (getItemTypeId() == null ? 0 : this.getItemTypeId()
						.hashCode());
		result = 37 * result
				+ (getDsicount() == null ? 0 : this.getDsicount().hashCode());
		result = 37 * result
				+ (getListPrice() == null ? 0 : this.getListPrice().hashCode());
		result = 37 * result + this.getOrderId();
		result = 37 * result
				+ (getBuyer() == null ? 0 : this.getBuyer().hashCode());
		result = 37 * result
				+ (getCreatorId() == null ? 0 : this.getCreatorId().hashCode());
		result = 37
				* result
				+ (getCustomerId() == null ? 0 : this.getCustomerId()
						.hashCode());
		result = 37
				* result
				+ (getCustomerPo() == null ? 0 : this.getCustomerPo()
						.hashCode());
		result = 37 * result
				+ (getFinishBy() == null ? 0 : this.getFinishBy().hashCode());
		result = 37
				* result
				+ (getFinishDate() == null ? 0 : this.getFinishDate()
						.hashCode());
		result = 37 * result
				+ (getInvoiceBy() == null ? 0 : this.getInvoiceBy().hashCode());
		result = 37
				* result
				+ (getInvoiceDate() == null ? 0 : this.getInvoiceDate()
						.hashCode());
		result = 37 * result
				+ (getOrderDate() == null ? 0 : this.getOrderDate().hashCode());
		result = 37 * result
				+ (getOrderName() == null ? 0 : this.getOrderName().hashCode());
		result = 37
				* result
				+ (getOrderNumber() == null ? 0 : this.getOrderNumber()
						.hashCode());
		result = 37
				* result
				+ (getOrderStatus() == null ? 0 : this.getOrderStatus()
						.hashCode());
		result = 37 * result
				+ (getOrderTime() == null ? 0 : this.getOrderTime().hashCode());
		result = 37 * result
				+ (getRepId() == null ? 0 : this.getRepId().hashCode());
		result = 37
				* result
				+ (getRequireDate() == null ? 0 : this.getRequireDate()
						.hashCode());
		result = 37
				* result
				+ (getRequireTime() == null ? 0 : this.getRequireTime()
						.hashCode());
		result = 37
				* result
				+ (getBusinessName() == null ? 0 : this.getBusinessName()
						.hashCode());
		result = 37 * result
				+ (getCreator() == null ? 0 : this.getCreator().hashCode());
		result = 37 * result
				+ (getRep() == null ? 0 : this.getRep().hashCode());
		result = 37 * result
				+ (getSnp() == null ? 0 : this.getSnp().hashCode());
		return result;
	}

}
