package test;

// Generated Mar 12, 2016 8:10:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderupcviewId generated by hbm2java
 */
@Embeddable
public class OrderupcviewId implements java.io.Serializable {

	@Column(name = "upcId")
	private Integer upcId;

	@Column(name = "orderQty")
	private Integer orderQty;

	@Column(name = "garmentId")
	private Integer garmentId;

	@Column(name = "styleNo", length = 20)
	private String styleNo;

	@Column(name = "styleName", length = 50)
	private String styleName;

	@Column(name = "brandId")
	private Integer brandId;

	@Column(name = "brand", length = 50)
	private String brand;

	@Column(name = "seasonId")
	private Integer seasonId;

	@Column(name = "season", length = 50)
	private String season;

	@Column(name = "category", length = 30)
	private String category;

	@Column(name = "upcNo", length = 12)
	private String upcNo;

	@Column(name = "colour", length = 50)
	private String colour;

	@Column(name = "size", length = 10)
	private String size;

	@Column(name = "qoh")
	private Integer qoh;

	@Column(name = "rrp", precision = 22, scale = 0)
	private Double rrp;

	@Column(name = "wsp", precision = 22, scale = 0)
	private Double wsp;

	@Column(name = "orderId", nullable = false)
	private int orderId;

	@Column(name = "buyer", length = 50)
	private String buyer;

	@Column(name = "creatorId")
	private Integer creatorId;

	@Column(name = "customerId")
	private Integer customerId;

	@Column(name = "customerPO", length = 50)
	private String customerPo;

	@Column(name = "finishBy")
	private Integer finishBy;

	@Column(name = "finishDate", length = 10)
	private Date finishDate;

	@Column(name = "invoiceBy")
	private Integer invoiceBy;

	@Column(name = "invoiceDate", length = 10)
	private Date invoiceDate;

	@Column(name = "orderDate", length = 10)
	private Date orderDate;

	@Column(name = "orderName", length = 100)
	private String orderName;

	@Column(name = "orderNumber", nullable = false, length = 20)
	private String orderNumber;

	@Column(name = "orderStatus")
	private Integer orderStatus;

	@Column(name = "orderTime", length = 8)
	private Date orderTime;

	@Column(name = "repId")
	private Integer repId;

	@Column(name = "requireDate", length = 10)
	private Date requireDate;

	@Column(name = "requireTime", length = 8)
	private Date requireTime;

	@Column(name = "businessName", length = 100)
	private String businessName;

	@Column(name = "creator", length = 511)
	private String creator;

	@Column(name = "rep", length = 511)
	private String rep;

	public OrderupcviewId() {
	}

	public OrderupcviewId(int orderId, String orderNumber) {
		this.orderId = orderId;
		this.orderNumber = orderNumber;
	}

	public OrderupcviewId(Integer upcId, Integer orderQty, Integer garmentId,
			String styleNo, String styleName, Integer brandId, String brand,
			Integer seasonId, String season, String category, String upcNo,
			String colour, String size, Integer qoh, Double rrp, Double wsp,
			int orderId, String buyer, Integer creatorId, Integer customerId,
			String customerPo, Integer finishBy, Date finishDate,
			Integer invoiceBy, Date invoiceDate, Date orderDate,
			String orderName, String orderNumber, Integer orderStatus,
			Date orderTime, Integer repId, Date requireDate, Date requireTime,
			String businessName, String creator, String rep) {
		this.upcId = upcId;
		this.orderQty = orderQty;
		this.garmentId = garmentId;
		this.styleNo = styleNo;
		this.styleName = styleName;
		this.brandId = brandId;
		this.brand = brand;
		this.seasonId = seasonId;
		this.season = season;
		this.category = category;
		this.upcNo = upcNo;
		this.colour = colour;
		this.size = size;
		this.qoh = qoh;
		this.rrp = rrp;
		this.wsp = wsp;
		this.orderId = orderId;
		this.buyer = buyer;
		this.creatorId = creatorId;
		this.customerId = customerId;
		this.customerPo = customerPo;
		this.finishBy = finishBy;
		this.finishDate = finishDate;
		this.invoiceBy = invoiceBy;
		this.invoiceDate = invoiceDate;
		this.orderDate = orderDate;
		this.orderName = orderName;
		this.orderNumber = orderNumber;
		this.orderStatus = orderStatus;
		this.orderTime = orderTime;
		this.repId = repId;
		this.requireDate = requireDate;
		this.requireTime = requireTime;
		this.businessName = businessName;
		this.creator = creator;
		this.rep = rep;
	}

	public Integer getUpcId() {
		return this.upcId;
	}

	public void setUpcId(Integer upcId) {
		this.upcId = upcId;
	}

	public Integer getOrderQty() {
		return this.orderQty;
	}

	public void setOrderQty(Integer orderQty) {
		this.orderQty = orderQty;
	}

	public Integer getGarmentId() {
		return this.garmentId;
	}

	public void setGarmentId(Integer garmentId) {
		this.garmentId = garmentId;
	}

	public String getStyleNo() {
		return this.styleNo;
	}

	public void setStyleNo(String styleNo) {
		this.styleNo = styleNo;
	}

	public String getStyleName() {
		return this.styleName;
	}

	public void setStyleName(String styleName) {
		this.styleName = styleName;
	}

	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public Integer getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(Integer seasonId) {
		this.seasonId = seasonId;
	}

	public String getSeason() {
		return this.season;
	}

	public void setSeason(String season) {
		this.season = season;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getUpcNo() {
		return this.upcNo;
	}

	public void setUpcNo(String upcNo) {
		this.upcNo = upcNo;
	}

	public String getColour() {
		return this.colour;
	}

	public void setColour(String colour) {
		this.colour = colour;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public Integer getQoh() {
		return this.qoh;
	}

	public void setQoh(Integer qoh) {
		this.qoh = qoh;
	}

	public Double getRrp() {
		return this.rrp;
	}

	public void setRrp(Double rrp) {
		this.rrp = rrp;
	}

	public Double getWsp() {
		return this.wsp;
	}

	public void setWsp(Double wsp) {
		this.wsp = wsp;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public String getBuyer() {
		return this.buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	public Integer getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getCustomerPo() {
		return this.customerPo;
	}

	public void setCustomerPo(String customerPo) {
		this.customerPo = customerPo;
	}

	public Integer getFinishBy() {
		return this.finishBy;
	}

	public void setFinishBy(Integer finishBy) {
		this.finishBy = finishBy;
	}

	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	public Integer getInvoiceBy() {
		return this.invoiceBy;
	}

	public void setInvoiceBy(Integer invoiceBy) {
		this.invoiceBy = invoiceBy;
	}

	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public Integer getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Integer getRepId() {
		return this.repId;
	}

	public void setRepId(Integer repId) {
		this.repId = repId;
	}

	public Date getRequireDate() {
		return this.requireDate;
	}

	public void setRequireDate(Date requireDate) {
		this.requireDate = requireDate;
	}

	public Date getRequireTime() {
		return this.requireTime;
	}

	public void setRequireTime(Date requireTime) {
		this.requireTime = requireTime;
	}

	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getRep() {
		return this.rep;
	}

	public void setRep(String rep) {
		this.rep = rep;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderupcviewId))
			return false;
		OrderupcviewId castOther = (OrderupcviewId) other;

		return ((this.getUpcId() == castOther.getUpcId()) || (this.getUpcId() != null
				&& castOther.getUpcId() != null && this.getUpcId().equals(
				castOther.getUpcId())))
				&& ((this.getOrderQty() == castOther.getOrderQty()) || (this
						.getOrderQty() != null
						&& castOther.getOrderQty() != null && this
						.getOrderQty().equals(castOther.getOrderQty())))
				&& ((this.getGarmentId() == castOther.getGarmentId()) || (this
						.getGarmentId() != null
						&& castOther.getGarmentId() != null && this
						.getGarmentId().equals(castOther.getGarmentId())))
				&& ((this.getStyleNo() == castOther.getStyleNo()) || (this
						.getStyleNo() != null && castOther.getStyleNo() != null && this
						.getStyleNo().equals(castOther.getStyleNo())))
				&& ((this.getStyleName() == castOther.getStyleName()) || (this
						.getStyleName() != null
						&& castOther.getStyleName() != null && this
						.getStyleName().equals(castOther.getStyleName())))
				&& ((this.getBrandId() == castOther.getBrandId()) || (this
						.getBrandId() != null && castOther.getBrandId() != null && this
						.getBrandId().equals(castOther.getBrandId())))
				&& ((this.getBrand() == castOther.getBrand()) || (this
						.getBrand() != null && castOther.getBrand() != null && this
						.getBrand().equals(castOther.getBrand())))
				&& ((this.getSeasonId() == castOther.getSeasonId()) || (this
						.getSeasonId() != null
						&& castOther.getSeasonId() != null && this
						.getSeasonId().equals(castOther.getSeasonId())))
				&& ((this.getSeason() == castOther.getSeason()) || (this
						.getSeason() != null && castOther.getSeason() != null && this
						.getSeason().equals(castOther.getSeason())))
				&& ((this.getCategory() == castOther.getCategory()) || (this
						.getCategory() != null
						&& castOther.getCategory() != null && this
						.getCategory().equals(castOther.getCategory())))
				&& ((this.getUpcNo() == castOther.getUpcNo()) || (this
						.getUpcNo() != null && castOther.getUpcNo() != null && this
						.getUpcNo().equals(castOther.getUpcNo())))
				&& ((this.getColour() == castOther.getColour()) || (this
						.getColour() != null && castOther.getColour() != null && this
						.getColour().equals(castOther.getColour())))
				&& ((this.getSize() == castOther.getSize()) || (this.getSize() != null
						&& castOther.getSize() != null && this.getSize()
						.equals(castOther.getSize())))
				&& ((this.getQoh() == castOther.getQoh()) || (this.getQoh() != null
						&& castOther.getQoh() != null && this.getQoh().equals(
						castOther.getQoh())))
				&& ((this.getRrp() == castOther.getRrp()) || (this.getRrp() != null
						&& castOther.getRrp() != null && this.getRrp().equals(
						castOther.getRrp())))
				&& ((this.getWsp() == castOther.getWsp()) || (this.getWsp() != null
						&& castOther.getWsp() != null && this.getWsp().equals(
						castOther.getWsp())))
				&& (this.getOrderId() == castOther.getOrderId())
				&& ((this.getBuyer() == castOther.getBuyer()) || (this
						.getBuyer() != null && castOther.getBuyer() != null && this
						.getBuyer().equals(castOther.getBuyer())))
				&& ((this.getCreatorId() == castOther.getCreatorId()) || (this
						.getCreatorId() != null
						&& castOther.getCreatorId() != null && this
						.getCreatorId().equals(castOther.getCreatorId())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this
						.getCustomerId() != null
						&& castOther.getCustomerId() != null && this
						.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCustomerPo() == castOther.getCustomerPo()) || (this
						.getCustomerPo() != null
						&& castOther.getCustomerPo() != null && this
						.getCustomerPo().equals(castOther.getCustomerPo())))
				&& ((this.getFinishBy() == castOther.getFinishBy()) || (this
						.getFinishBy() != null
						&& castOther.getFinishBy() != null && this
						.getFinishBy().equals(castOther.getFinishBy())))
				&& ((this.getFinishDate() == castOther.getFinishDate()) || (this
						.getFinishDate() != null
						&& castOther.getFinishDate() != null && this
						.getFinishDate().equals(castOther.getFinishDate())))
				&& ((this.getInvoiceBy() == castOther.getInvoiceBy()) || (this
						.getInvoiceBy() != null
						&& castOther.getInvoiceBy() != null && this
						.getInvoiceBy().equals(castOther.getInvoiceBy())))
				&& ((this.getInvoiceDate() == castOther.getInvoiceDate()) || (this
						.getInvoiceDate() != null
						&& castOther.getInvoiceDate() != null && this
						.getInvoiceDate().equals(castOther.getInvoiceDate())))
				&& ((this.getOrderDate() == castOther.getOrderDate()) || (this
						.getOrderDate() != null
						&& castOther.getOrderDate() != null && this
						.getOrderDate().equals(castOther.getOrderDate())))
				&& ((this.getOrderName() == castOther.getOrderName()) || (this
						.getOrderName() != null
						&& castOther.getOrderName() != null && this
						.getOrderName().equals(castOther.getOrderName())))
				&& ((this.getOrderNumber() == castOther.getOrderNumber()) || (this
						.getOrderNumber() != null
						&& castOther.getOrderNumber() != null && this
						.getOrderNumber().equals(castOther.getOrderNumber())))
				&& ((this.getOrderStatus() == castOther.getOrderStatus()) || (this
						.getOrderStatus() != null
						&& castOther.getOrderStatus() != null && this
						.getOrderStatus().equals(castOther.getOrderStatus())))
				&& ((this.getOrderTime() == castOther.getOrderTime()) || (this
						.getOrderTime() != null
						&& castOther.getOrderTime() != null && this
						.getOrderTime().equals(castOther.getOrderTime())))
				&& ((this.getRepId() == castOther.getRepId()) || (this
						.getRepId() != null && castOther.getRepId() != null && this
						.getRepId().equals(castOther.getRepId())))
				&& ((this.getRequireDate() == castOther.getRequireDate()) || (this
						.getRequireDate() != null
						&& castOther.getRequireDate() != null && this
						.getRequireDate().equals(castOther.getRequireDate())))
				&& ((this.getRequireTime() == castOther.getRequireTime()) || (this
						.getRequireTime() != null
						&& castOther.getRequireTime() != null && this
						.getRequireTime().equals(castOther.getRequireTime())))
				&& ((this.getBusinessName() == castOther.getBusinessName()) || (this
						.getBusinessName() != null
						&& castOther.getBusinessName() != null && this
						.getBusinessName().equals(castOther.getBusinessName())))
				&& ((this.getCreator() == castOther.getCreator()) || (this
						.getCreator() != null && castOther.getCreator() != null && this
						.getCreator().equals(castOther.getCreator())))
				&& ((this.getRep() == castOther.getRep()) || (this.getRep() != null
						&& castOther.getRep() != null && this.getRep().equals(
						castOther.getRep())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUpcId() == null ? 0 : this.getUpcId().hashCode());
		result = 37 * result
				+ (getOrderQty() == null ? 0 : this.getOrderQty().hashCode());
		result = 37 * result
				+ (getGarmentId() == null ? 0 : this.getGarmentId().hashCode());
		result = 37 * result
				+ (getStyleNo() == null ? 0 : this.getStyleNo().hashCode());
		result = 37 * result
				+ (getStyleName() == null ? 0 : this.getStyleName().hashCode());
		result = 37 * result
				+ (getBrandId() == null ? 0 : this.getBrandId().hashCode());
		result = 37 * result
				+ (getBrand() == null ? 0 : this.getBrand().hashCode());
		result = 37 * result
				+ (getSeasonId() == null ? 0 : this.getSeasonId().hashCode());
		result = 37 * result
				+ (getSeason() == null ? 0 : this.getSeason().hashCode());
		result = 37 * result
				+ (getCategory() == null ? 0 : this.getCategory().hashCode());
		result = 37 * result
				+ (getUpcNo() == null ? 0 : this.getUpcNo().hashCode());
		result = 37 * result
				+ (getColour() == null ? 0 : this.getColour().hashCode());
		result = 37 * result
				+ (getSize() == null ? 0 : this.getSize().hashCode());
		result = 37 * result
				+ (getQoh() == null ? 0 : this.getQoh().hashCode());
		result = 37 * result
				+ (getRrp() == null ? 0 : this.getRrp().hashCode());
		result = 37 * result
				+ (getWsp() == null ? 0 : this.getWsp().hashCode());
		result = 37 * result + this.getOrderId();
		result = 37 * result
				+ (getBuyer() == null ? 0 : this.getBuyer().hashCode());
		result = 37 * result
				+ (getCreatorId() == null ? 0 : this.getCreatorId().hashCode());
		result = 37
				* result
				+ (getCustomerId() == null ? 0 : this.getCustomerId()
						.hashCode());
		result = 37
				* result
				+ (getCustomerPo() == null ? 0 : this.getCustomerPo()
						.hashCode());
		result = 37 * result
				+ (getFinishBy() == null ? 0 : this.getFinishBy().hashCode());
		result = 37
				* result
				+ (getFinishDate() == null ? 0 : this.getFinishDate()
						.hashCode());
		result = 37 * result
				+ (getInvoiceBy() == null ? 0 : this.getInvoiceBy().hashCode());
		result = 37
				* result
				+ (getInvoiceDate() == null ? 0 : this.getInvoiceDate()
						.hashCode());
		result = 37 * result
				+ (getOrderDate() == null ? 0 : this.getOrderDate().hashCode());
		result = 37 * result
				+ (getOrderName() == null ? 0 : this.getOrderName().hashCode());
		result = 37
				* result
				+ (getOrderNumber() == null ? 0 : this.getOrderNumber()
						.hashCode());
		result = 37
				* result
				+ (getOrderStatus() == null ? 0 : this.getOrderStatus()
						.hashCode());
		result = 37 * result
				+ (getOrderTime() == null ? 0 : this.getOrderTime().hashCode());
		result = 37 * result
				+ (getRepId() == null ? 0 : this.getRepId().hashCode());
		result = 37
				* result
				+ (getRequireDate() == null ? 0 : this.getRequireDate()
						.hashCode());
		result = 37
				* result
				+ (getRequireTime() == null ? 0 : this.getRequireTime()
						.hashCode());
		result = 37
				* result
				+ (getBusinessName() == null ? 0 : this.getBusinessName()
						.hashCode());
		result = 37 * result
				+ (getCreator() == null ? 0 : this.getCreator().hashCode());
		result = 37 * result
				+ (getRep() == null ? 0 : this.getRep().hashCode());
		return result;
	}

}
