package test;

// Generated Mar 12, 2016 8:10:40 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Orderbillitemview generated by hbm2java
 */
@Entity
@Table(name = "orderbillitemview", catalog = "world")
public class Orderbillitemview implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rowId", column = @Column(name = "rowId", nullable = false)),
			@AttributeOverride(name = "description", column = @Column(name = "description")),
			@AttributeOverride(name = "finishAmt", column = @Column(name = "finishAmt")),
			@AttributeOverride(name = "finishQty", column = @Column(name = "finishQty")),
			@AttributeOverride(name = "invoiceAmt", column = @Column(name = "invoiceAmt")),
			@AttributeOverride(name = "invoicePrice", column = @Column(name = "invoicePrice")),
			@AttributeOverride(name = "invoiceQty", column = @Column(name = "invoiceQty")),
			@AttributeOverride(name = "itemNumber", column = @Column(name = "itemNumber", length = 20)),
			@AttributeOverride(name = "lineNo", column = @Column(name = "lineNo")),
			@AttributeOverride(name = "orderAmt", column = @Column(name = "orderAmt")),
			@AttributeOverride(name = "orderItemId", column = @Column(name = "orderItemId")),
			@AttributeOverride(name = "orderPrice", column = @Column(name = "orderPrice")),
			@AttributeOverride(name = "orderQty", column = @Column(name = "orderQty")),
			@AttributeOverride(name = "remark", column = @Column(name = "remark")),
			@AttributeOverride(name = "snpId", column = @Column(name = "snpId")),
			@AttributeOverride(name = "unit", column = @Column(name = "unit", length = 20)),
			@AttributeOverride(name = "billingKey", column = @Column(name = "billingKey", length = 20)),
			@AttributeOverride(name = "itemTypeId", column = @Column(name = "itemTypeId")),
			@AttributeOverride(name = "dsicount", column = @Column(name = "dsicount")),
			@AttributeOverride(name = "listPrice", column = @Column(name = "listPrice")),
			@AttributeOverride(name = "orderId", column = @Column(name = "orderId", nullable = false)),
			@AttributeOverride(name = "buyer", column = @Column(name = "buyer", length = 50)),
			@AttributeOverride(name = "creatorId", column = @Column(name = "creatorId")),
			@AttributeOverride(name = "customerId", column = @Column(name = "customerId")),
			@AttributeOverride(name = "customerPo", column = @Column(name = "customerPO", length = 50)),
			@AttributeOverride(name = "finishBy", column = @Column(name = "finishBy")),
			@AttributeOverride(name = "finishDate", column = @Column(name = "finishDate", length = 10)),
			@AttributeOverride(name = "invoiceBy", column = @Column(name = "invoiceBy")),
			@AttributeOverride(name = "invoiceDate", column = @Column(name = "invoiceDate", length = 10)),
			@AttributeOverride(name = "orderDate", column = @Column(name = "orderDate", length = 10)),
			@AttributeOverride(name = "orderName", column = @Column(name = "orderName", length = 100)),
			@AttributeOverride(name = "orderNumber", column = @Column(name = "orderNumber", nullable = false, length = 20)),
			@AttributeOverride(name = "orderStatus", column = @Column(name = "orderStatus")),
			@AttributeOverride(name = "orderTime", column = @Column(name = "orderTime", length = 8)),
			@AttributeOverride(name = "repId", column = @Column(name = "repId")),
			@AttributeOverride(name = "requireDate", column = @Column(name = "requireDate", length = 10)),
			@AttributeOverride(name = "requireTime", column = @Column(name = "requireTime", length = 8)),
			@AttributeOverride(name = "businessName", column = @Column(name = "businessName", length = 100)),
			@AttributeOverride(name = "creator", column = @Column(name = "creator", length = 511)),
			@AttributeOverride(name = "rep", column = @Column(name = "rep", length = 511)),
			@AttributeOverride(name = "snp", column = @Column(name = "snp", length = 50)) })
	private OrderbillitemviewId id;

	public Orderbillitemview() {
	}

	public Orderbillitemview(OrderbillitemviewId id) {
		this.id = id;
	}

	public OrderbillitemviewId getId() {
		return this.id;
	}

	public void setId(OrderbillitemviewId id) {
		this.id = id;
	}

}
