package com.scdeco.miniataweb.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class OrderBillItem extends CliviaSuperModel{
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	@Column(name="OrderId")
	private int orderId;
	
	@Column(name="OrderItemId")
	private int orderItemId;
	
	@Column(name="LineNo")
	private int lineNo;	
	
	@Column(name="SnpId")
	private int snpId;
	
	//if >0, this is an auto generated item from orderItemTypeId,like 2 stannds for lineItem 
	@Column(name="ItemTypeId")
	private Integer itemTypeId;

	//key of autogenerated item, for example if itemTypeId=2, then this item is from a lineItem and billingKey should be a string of garmentId
	@Column(name="BillingKey", length=100)
	private String billingKey;
	
	//billing keys, like style# for DD lineItems(itemTypeId=2),or design# for deco items
	@Column(name="ItemNumber", length=20)
	private String itemNumber;
	
	@Column(name="Description")
	private String description;	
	
	@Column(name="OrderQty")
	private  BigDecimal orderQty;
	
	@Column(name="FinishQty")
	private BigDecimal finishQty;
	
	@Column(name="InvoiceQty")
	private BigDecimal invoiceQty;
	
	@Column(name="Unit", length=20)
	private String unit;

	@Column(name="ListPrice")
	private BigDecimal listPrice;

	//percentage off
	@Column(name="Dsicount")
	private BigDecimal discount;

	@Column(name="OrderPrice")
	private BigDecimal orderPrice;
	
	@Column(name="InvoicePrice")
	private BigDecimal invoicePrice;
	
	@Column(name="OrderAmt")
	private BigDecimal orderAmt;
	
	@Column(name="FinishAmt")
	private BigDecimal finishAmt;
	
	@Column(name="InvoiceAmt")
	private BigDecimal invoiceAmt;
	
	@Column(name="Remark")
	private String remark;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getOrderId() {
		return orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getOrderItemId() {
		return orderItemId;
	}

	public void setOrderItemId(int orderItemId) {
		this.orderItemId = orderItemId;
	}

	public int getLineNo() {
		return lineNo;
	}

	public void setLineNo(int lineNo) {
		this.lineNo = lineNo;
	}

	public int getSnpId() {
		return snpId;
	}

	public void setSnpId(int snpId) {
		this.snpId = snpId;
	}

	public Integer getItemTypeId() {
		return itemTypeId;
	}

	public void setItemTypeId(Integer itemTypeId) {
		this.itemTypeId = itemTypeId;
	}

	public String getBillingKey() {
		return billingKey;
	}

	public void setBillingKey(String billingKey) {
		this.billingKey = billingKey;
	}

	public String getItemNumber() {
		return itemNumber;
	}

	public void setItemNumber(String itemNumber) {
		this.itemNumber = itemNumber;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getOrderQty() {
		return orderQty;
	}

	public void setOrderQty(BigDecimal orderQty) {
		this.orderQty = orderQty;
	}

	public BigDecimal getFinishQty() {
		return finishQty;
	}

	public void setFinishQty(BigDecimal finishQty) {
		this.finishQty = finishQty;
	}

	public BigDecimal getInvoiceQty() {
		return invoiceQty;
	}

	public void setInvoiceQty(BigDecimal invoiceQty) {
		this.invoiceQty = invoiceQty;
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public BigDecimal getListPrice() {
		return listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	public BigDecimal getDiscount() {
		return discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public BigDecimal getOrderPrice() {
		return orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	public BigDecimal getInvoicePrice() {
		return invoicePrice;
	}

	public void setInvoicePrice(BigDecimal invoicePrice) {
		this.invoicePrice = invoicePrice;
	}

	public BigDecimal getOrderAmt() {
		return orderAmt;
	}

	public void setOrderAmt(BigDecimal orderAmt) {
		this.orderAmt = orderAmt;
	}

	public BigDecimal getFinishAmt() {
		return finishAmt;
	}

	public void setFinishAmt(BigDecimal finishAmt) {
		this.finishAmt = finishAmt;
	}

	public BigDecimal getInvoiceAmt() {
		return invoiceAmt;
	}

	public void setInvoiceAmt(BigDecimal invoiceAmt) {
		this.invoiceAmt = invoiceAmt;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}


	
}
